#!/usr/bin/env python3
"""Extracts QuantLib's own reference tables into reference_tables.py.

The tables in test-suite/*.cpp are the published values this service is
checked against. Transcribing them by hand is how a benchmark quietly stops
benchmarking: a digit changes and the test still passes, against the wrong
number. So they are parsed out of the C++ instead, and the parser is checked
in beside the result.

Usage:
    python3 test/extract_tables.py ~/CLionProjects/QuantLib > test/reference_tables.py

The output is committed. Re-run it when the QuantLib checkout moves, and the
diff is then the library's change rather than ours.
"""

import re
import sys
from pathlib import Path

# (module name, source file, C++ declaration, field names)
#
# Field names follow the C++ struct member for member, including the ones we
# do not use, so a row can be read against the source without counting commas.
TABLES = [
    ("EUROPEAN", "europeanoption.cpp", "EuropeanOptionData values[]",
     "type strike s q r t v result tol"),
    ("AMERICAN_BAW", "americanoption.cpp", "AmericanOptionData values[]",
     "type strike s q r t v result", 0),
    ("AMERICAN_BS", "americanoption.cpp", "AmericanOptionData values[]",
     "type strike s q r t v result", 1),
    ("AMERICAN_JU", "americanoption.cpp", "AmericanOptionData juValues[]",
     "type strike s q r t v result"),
    ("BARRIER", "barrieroption.cpp", "NewBarrierOptionData values[]",
     "barrier_type barrier rebate type exercise strike s q r t v result tol"),
    ("FORWARD", "forwardoption.cpp", "ForwardOptionData values[]",
     "type moneyness s q r start t v result tol"),
    ("QUANTO", "quantooption.cpp", "QuantoOptionData values[]",
     "type strike s q r t v fxr fxv corr result tol"),
    ("QUANTO_FORWARD", "quantooption.cpp", "QuantoForwardOptionData values[]",
     "type moneyness s q r start t v fxr fxv corr result tol"),
    ("QUANTO_BARRIER", "quantooption.cpp", "QuantoBarrierOptionData values[]",
     "barrier_type barrier rebate type s strike q r t v fxr fxv corr result tol"),
    ("QUANTO_DOUBLE_BARRIER", "quantooption.cpp", "QuantoDoubleBarrierOptionData values[]",
     "barrier_type barrier_lo barrier_hi rebate type s strike q r t v fxr fxv corr result tol"),
    # Occurrence 1: the first table in the file is the put-call parity one,
    # which carries no published price -- it checks a relation rather than a
    # number, so there is nothing in it to price against.
    ("COMPOUND", "compoundoption.cpp", "CompoundOptionData values[]",
     "typeMother typeDaughter strikeMother strikeDaughter s q r tMother tDaughter v"
     " npv tol delta gamma vega theta", 1),
]

# C++ spellings that are not numbers. Mapped to the strings the smoke scripts
# use, never to the proto enum values: those are deliberately not QuantLib's
# own numbers, and a table that hardcoded them would silently follow a
# renumbering (conventions.proto).
WORDS = {
    "Option::Call": "'call'",
    "Option::Put": "'put'",
    "Barrier::DownIn": "'down_in'",
    "Barrier::UpIn": "'up_in'",
    "Barrier::DownOut": "'down_out'",
    "Barrier::UpOut": "'up_out'",
    "DoubleBarrier::KnockIn": "'knock_in'",
    "DoubleBarrier::KnockOut": "'knock_out'",
    "DoubleBarrier::KIKO": "'kiko'",
    "DoubleBarrier::KOKI": "'koki'",
    "european": "'european'",
    "american": "'american'",
    "Exercise::European": "'european'",
    "Exercise::American": "'american'",
    "true": "True",
    "false": "False",
}


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def find_table(text, declaration, occurrence=0):
    """The brace-balanced body of the nth `declaration = { ... };`."""
    starts = [m.end() for m in re.finditer(re.escape(declaration) + r"\s*=\s*\{",
                                           text)]
    if len(starts) <= occurrence:
        raise SystemExit(f"no occurrence {occurrence} of {declaration!r}")
    i = starts[occurrence]
    depth = 1
    out = []
    while depth:
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                break
        out.append(c)
        i += 1
    return "".join(out)


def parse_rows(body, fields):
    rows = []
    for match in re.finditer(r"\{([^{}]*)\}", body):
        cells = [c.strip() for c in match.group(1).split(",")]
        cells = [c for c in cells if c != ""]
        if len(cells) != len(fields):
            raise SystemExit(
                f"row has {len(cells)} cells, expected {len(fields)}: {cells}")
        rows.append([WORDS.get(c, c) for c in cells])
    return rows


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    root = Path(sys.argv[1]).expanduser() / "test-suite"

    print('"""QuantLib\'s own reference tables, extracted from its test suite.')
    print()
    print("GENERATED by test/extract_tables.py -- do not edit by hand.")
    print()
    print("Each row is a dict keyed by the C++ struct's own member names, so a")
    print("row can be read against the source without counting commas. `result`")
    print("is the published value and `tol` the tolerance the C++ test uses;")
    print("neither is tightened here, because those numbers are what is under")
    print('test.')
    print('"""')
    print()

    for spec in TABLES:
        name, filename, declaration, fields = spec[:4]
        occurrence = spec[4] if len(spec) > 4 else 0
        fields = fields.split()

        text = strip_comments((root / filename).read_text())
        rows = parse_rows(find_table(text, declaration, occurrence), fields)

        print(f"# {filename}: {declaration}"
              + (f" [{occurrence}]" if occurrence else ""))
        print(f"{name} = [")
        for row in rows:
            pairs = ", ".join(f"{f}={v}" for f, v in zip(fields, row))
            print(f"    dict({pairs}),")
        print("]")
        print()

    print("TABLES = {")
    for spec in TABLES:
        print(f"    {spec[0]!r}: {spec[0]},")
    print("}")


if __name__ == "__main__":
    main()
